#Vectors and Matrrices
Linear algebra is a branch of mathematics that deals with vectors,matrices and linear transformations. It plays a crucial role in datascience, particularly in machine learning where ir is used to perform various operations on data.

#Vectors
-A vector is an ordered collection of numbers, which can represent a point in space or a set of values.
-A vector is often denoted by a  bold letter(printed text) OR a lowercase letter with an arrow on top.(written text).

In [ ]:
import numpy as np

vector_2d = np.array([2,3])
print(vector_2d)

[2 3]


Vector Addition

. vectors of the same dmension can be added element-wise.

In [ ]:
vector_1 = np.array([1,2,3])
vector_2 = np.array([4,5,6])

vector_sum = vector_1 + vector_2
print(vector_sum)

[5 7 9]


Scalar multiplication

In [ ]:
vector_1 =np.array([1,2,3])
scalar_digit = 3

print(vector_1* scalar_digit)

[3 6 9]


Dot product(multiplication)

#Matrices
-A matrix is a rectangular array of numbers that are arranged in rows and columns. It can represent linear transformations, data and etc.

-A matrix is denoted by a capital letter such as A, B or C. The elments within a matrix are enclosed in a square bracket or parentheses. The dimensions of a matrix are specified by the number of rows and columns.

In [ ]:
matrix_3_by_3 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
print(matrix_3_by_3)
print(matrix_3_by_3[0][1][0])

Matrix addition

-Matrices of the same dimension can be added element wise.


In [ ]:
matrix_A = np.array([
    [1,2],
    [3,4]
])
matrix_B = np.array([
    [5,6],
    [7,8]
])

print(matrix_A + matrix_B)

[[ 6  8]
 [10 12]]


In [ ]:
#indices start from 0
#rows before columns
print(matrix_A[1][1])

4


Matrix Multiplication
.Multiplication - element wise multiplication

.Dot product

In [ ]:
matrix_A = np.array([
    [1,2],
    [3,4]
])
matrix_B = np.array([
    [5,6],
    [7,8]
])

print(matrix_A * matrix_B)


[[ 5 12]
 [21 32]]


Create a pythin function that takes in two 2*2 matrices and computes their dot product. Do not use the .dot()

In [ ]:


def calculate_dot_product(matrix_1, matrix_2):
  a = (matrix_1[0][0])
  b = (matrix_1[0][1])
  c = (matrix_1[1][0])
  d = (matrix_1[1][1])

  e = (matrix_2[0][0])
  f = (matrix_2[0][1])
  g = (matrix_2[1][0])
  h = (matrix_2[1][1])

  one = a*e + b*g
  two = a*f + b*h
  three = c*e + d*g
  four = c*f + d*h


  result = ([a*e + b*g, a*f + b*h],
            [c*e + d*g, c*f + d*h])
  return np.array(result)

matrix_A = ([
    [1,2],
    [3,4]
])

matrix_B = ([
    [5,6],
    [7,8]
])

result= calculate_dot_product(matrix_A, matrix_B)
print(result)


[[19 22]
 [43 50]]


3*3 matrix

In [ ]:
import numpy as np

def calculate_dot_product(matrix_1, matrix_2):

    a = matrix_1[0][0]
    b = matrix_1[0][1]
    c = matrix_1[0][2]
    d = matrix_1[1][0]
    e = matrix_1[1][1]
    f = matrix_1[1][2]
    g = matrix_1[2][0]
    h = matrix_1[2][1]
    i = matrix_1[2][2]


    j = matrix_2[0][0]
    k = matrix_2[0][1]
    l = matrix_2[0][2]
    m = matrix_2[1][0]
    n = matrix_2[1][1]
    o = matrix_2[1][2]
    p = matrix_2[2][0]
    q = matrix_2[2][1]
    r = matrix_2[2][2]


    one   = a*j + b*m + c*p
    two   = a*k + b*n + c*q
    three = a*l + b*o + c*r

    four  = d*j + e*m + f*p
    five  = d*k + e*n + f*q
    six   = d*l + e*o + f*r

    seven = g*j + h*m + i*p
    eight = g*k + h*n + i*q
    nine  = g*l + h*o + i*r


    result = ([one, two, three],
              [four, five, six],
              [seven, eight, nine])

    return np.array(result)



matrix_A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix_B = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

result = calculate_dot_product(matrix_A, matrix_B)
print(result)


[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Identity Matrix - square matrix(has same no of rows and columns)where all values in main diagonal are 1 and all other values are 0.


In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Inverse of a matrix

. For a matrix A , the inverse A*-1 is such that  AA*-1 = identity matrix

In [ ]:
matrix_A= np.array([
    [7,2],
    [17,5]
])
inverse_matrix_A = np.linalg.inv(matrix_A)
print(inverse_matrix_A)
#print(matrix_A.shape[1])

[[  5.  -2.]
 [-17.   7.]]
2


inverse = 1/determinant*(main diagonal swapped ,other diagonals negated).

Determinant = difference of the product of the main diagonal and other diagonal




In [ ]:
import numpy as np

def calculate_inverse_2x2(matrix):

  a, b = matrix[0]
  c, d = matrix[1]

  determinant = a * d - b * c

  if determinant == 0:
    return "The matrix is not invertible."

  inverse_determinant = 1 / determinant


  inverse_matrix = np.array([
      [d, -b],
      [-c, a]
  ]) * inverse_determinant

  return inverse_matrix

matrix_A = np.array([
    [7, 2],
    [17, 5]
])

inverse_A = calculate_inverse_2x2(matrix_A)
print(inverse_A)

matrix_B = np.array([
    [1, 2],
    [3, 4]
])

inverse_B = calculate_inverse_2x2(matrix_B)
print(inverse_B)

[[  5.  -2.]
 [-17.   7.]]
[[-2.   1. ]
 [ 1.5 -0.5]]


1. Create a python function that takes in a single matrix parameter and checks whether it is an identity matrix or not.

For matrices, to check whether 2 matrices are equal to each other we do not use ==, rather use np.array_equal(matrix_A,matrix_B)

2. Define a python function that calculates the inverse of a 2*2 matrix.

In [ ]:
import numpy as np

def is_identity(matrix_A):
  rows = matrix_A.shape[0]
  columns = matrix_A.shape[1]
  if rows == columns:
    id_matrix = np.eye(rows)
    if np.array_equal(matrix_A, id_matrix):
      return True
    else:
      return False
  else:
    return False

matrix_A = np.array([
    [1,0],
    [0,1]
])

if is_identity(matrix_A):
  print(f"{matrix_A} is an identity matrix")
else:
  print(f"{matrix_A} is not an identity matrix")






[[1 0]
 [0 1]] is an identity matrix


In [ ]:
def inv_2_2(matrix_1):
  a = (matrix_1[0][0])
  b = (matrix_1[0][1])
  c = (matrix_1[1][0])
  d = (matrix_1[1][1])
  determinant = a*d - b*c
  main_swapped_negated = np.array([
      [d,-b],
      [-c,a]
  ])

  inverse_matrix = 1/determinant * main_swapped_negated
  return inverse_matrix

matrix_1 = np.array([
    [7,2],
    [17,5]
])
calculated_inverse= inv_2_2(matrix_1)
print(np.dot(matrix_1,calculated_inverse))

[[1. 0.]
 [0. 1.]]


Transpose of a matrix

.It is obtained by swapping the rows and the columns.

In [ ]:
matrix_A = np.array([
    [7,2,1],
    [17,5,4]
])
print(matrix_A.T)

[[ 7 17]
 [ 2  5]
 [ 1  4]]


Write a python script that takes inputs from a user for the elements within a 2*2 square matrix, save the resultant matrix as a variable.

Use your defined functions to get the following:
. Check whether it is an identity matrix

. Calculate the inverse of the 2*2 matrix.

.Assertain that for a matrix A, the inverse  A**-1 is such that AA*-1 = identity matrix.

Print the transpose of the matrix.

In [ ]:
a = int(input("Enter the value of a at position [0][0]: "))
b = int(input("Enter the value of b at position [0][1]: "))
c = int(input("Enter the value of c at position [1][0]: "))
d = int(input("Enter the value of d at position [1][1]: "))

matrix =np.array ([
    [a, b],
    [c ,d]
])

print(f""" Matrix A :
 {matrix}
      """)

if is_identity(matrix):
  print(f"{matrix} is an identity matrix")
else:
  print(f"{matrix} is not an identity matrix")

  calc_inverse = inv_2_2(matrix)
  print(f"""The inverse of matrix is :
  {calc_inverse}""")

print(f"""Te transposition of matrix is :
{matrix.T}""")

Solving simultaneous linear equations
1. Substitution
2. Elimination
3. Matrix method

# Substitution

Equation 1: 2x +3y = 9

Equation 2: x - y = 3

x = 3 + y

2( 3 + y) + 3y = 9

6+ 2y + 3y = 9

5y = 3

y = 0.6

recall: x = 3+ y ; x = 3 0.6
x = 3.6

#Elimination
(2x + 3y = 9) *1

(x - y = 3)*2

2x + 3y = 9

2x - 2y = 6

x + 5y = 3
 y = 0.6

 x - 0.6 = 3

In [ ]:
matrix_A = np.array([
    [2,3],
    [1,-1]
])

results = np.array([9,3])

solution = np.linalg.solve(matrix_A, results)
x = solution[0]
y = solution [1]
print(f"(x,y) = ({x}, {y})")



(x,y) = (3.6, 0.6)


Create a python function that calculates the solutions to x and y for simultaneous linear equations whose values are obtained from user inputs.

In [ ]:
def solve_linear_equations(matrix_A, results):
 solution = np.linalg.solve(matrix, results)
 x = solution[0]
 y = solution [1]
 return x, y


a = int(input("Enter the value of x at position [0][0]: "))
b = int(input("Enter the value of y at position [0][1]: "))
result_first = int(input("Enter the result of the first equation: "))
c = int(input("Enter the value of x at position [1][0]: "))
d = int(input("Enter the value of y at position [1][1]: "))
result_second = int(input("Enter the result of the second equation: "))

matrix =np.array ([
  [a, b],
  [c ,d]
])
results = np.array([result_first , result_second])
x,y = solve_linear_equations(matrix_A, results)
print(f"(x,y) = ({x}, {y})")



Enter the value of x at position [0][0]: 2
Enter the value of y at position [0][1]: 3
Enter the result of the first equation: 9
Enter the value of x at position [1][0]: 1
Enter the value of y at position [1][1]: -1
Enter the result of the second equation: 3
(x,y) = (3.6, 0.6)


Areas of Application of Linear Algebra in Data Science

1. PCA- Principal Component Analysis
-this is a dimensionality reduction technique, which is used to reduce the number of dimensions in a given dataset, while preserving variance.
2. Linear Regression uses linear algebra to get the coefficients of a line of bets fit. y = mx+c
m is gradient of the line and c is the y intercept.
3. Feature scaling/ normalization/ standardization shrinking or stretching
data to fixed range of values for better processing.
Age - 20,25,40,60,80
networth-
4. Gradient Descent  is an optimization algorithm that is used to reduce the cost/loss function by tuning coefficients m and c so as to get optimal performance of the model.
5. Computer Vision
coloured images - 3 colour schemes/ channels -RGB
Grayscale images - 1 colour channel - white (0 - 255)

Machine Learning

-Supervised Machine Learning - train a machine learning model on labelled data
1. Regression - target is continuous numerical data.
2. Classification - target is a set of non-changing categories.

 eg Country, company, model ,year, CC, Torque, Transmission, Price

-Unsupervised machine learning - train a machine learning model on unllabeled data.
1. Clustering - grouping together similar datapoints.
2. Dimensionality Reduction - Reducing the number of dimensions in a dataset while maintaining variables