#Numpy
Numerical python. It is foundational for numerical computation using the python programming language.
- Is designed for scientific computation and is ised extensively for data analysis to handle large ,multidimensional arrays and matrices efficiently.
- Serves as a basis for many python data science libraries; including pandas, due to its speed and efficiency in numerical operations.
- A few special cases for Numpy especially in data analysis include:
1. Array operations
2. Linear algebra
3. Statistical functions
4. Random number Generation


#Array Operations
. ,+,-,*,/,//,etc

In [ ]:
!pip install numpy


In [ ]:
import numpy as np

years_of_experience = np.array([1,2,3,4,5])
years_of_experience_plus_1 = years_of_experience + 1

print(years_of_experience_plus_1)


[2 3 4 5 6]


Converting a column from USD to  KSH

In [ ]:
usd_values = np.array([3.99,5.99,9.99,14.99,19.99])
ksh_values = usd_values*129.30
print(ksh_values)

[ 515.907  774.507 1291.707 1938.207 2584.707]


In [ ]:
print(usd_values)

[ 3.99  5.99  9.99 14.99 19.99]


In [ ]:
print(type(usd_values[1:4]))

<class 'numpy.ndarray'>


Boolean indexing(Conditional Filtering)
.Get the subset of values that satisfy a particular condition

Syntax:

data[condition]

In [ ]:
years_of_experience = np.array([1,2,3,4,5])
more_than_3 = years_of_experience[years_of_experience > 3]
print(more_than_3)

[4 5]


In [ ]:
random_numbers = np.array([20, 40,55,89,51,28])

even_numbers = random_numbers[random_numbers % 2 == 0]
odd_numbers = random_numbers[random_numbers % 2 != 0]

print(f"odd_numbers:{odd_numbers}")
print(f"even_numbers;{even_numbers}")


odd_numbers:[55 89 51]
even_numbers;[20 40 28]


1. Create a python script that takes 6 number inputs from the user on heights of different people in cm. It then returns a numpy.ndarray of the heights in feet.
2. Create a python script that takes 6 inputs from the user on ages of different people and returns the age they were on the onset of covid 19 in
the country.
3. Filter out the heigts on question 1 that are less than 5.5 feet.
4. Filter out the heights on question 1 that are more than 6 feet.
5. Hard code a np.array of 10 values and filter out the positive numbers and negative numbers.

In [ ]:
import numpy as np

h1 =int(input("Enter your height in cm:"))
h2 =int(input("Enter your heigh in cmt:"))
h3 =int(input("Enter your height in cm:"))
h4 =int(input("Enter your height in cm:"))
h5 =int(input("Enter your height in cm:"))
h6 =int(input("Enter your height in cm:"))

height_in_cm =np.array ([h1,h2,h3,h4,h5,h6])
height_in_feet = height_in_cm / 30.48

print(f"{height_in_feet} and is of the datatype {type(height_in_feet)}")

less_5_5 = height_in_feet[height_in_feet<5.5]
more_6_feet = height_in_feet[height_in_feet>6]
print(f"{less_5_5}")
print(f"{more_6_feet}")



Enter your height in cm:170
Enter your heigh in cmt:155
Enter your height in cm:157
Enter your height in cm:165
Enter your height in cm:162
Enter your height in cm:177
[5.57742782 5.08530184 5.15091864 5.41338583 5.31496063 5.80708661] and is of the datatype <class 'numpy.ndarray'>
[5.08530184 5.15091864 5.41338583 5.31496063]
[]


In [ ]:
age1=float(input("Enter your age:"))
age2=float(input("Enter your age:"))
age3=float(input("Enter your age:"))
age4=float(input("Enter your age:"))
age5=float(input("Enter your age:"))
age6=float(input("Enter your age:"))

ages = np.array([age1,age2,age3,age4,age5,age6])
current_year = 2025
onset_covid= 2020
years_elapsed = current_year-onset_covid
covid_ages = ages - years_elapsed
print(f"{covid_ages} and is of datatype {type(covid_ages)}")


Enter your age:45
Enter your age:22
Enter your age:30
Enter your age:29
Enter your age:37
Enter your age:65
[40. 17. 25. 24. 32. 60.] and is of datatype <class 'numpy.ndarray'>


In [ ]:
numbers = (np.array[10,-15,46,-77,89,-90,48,38,65,-22])

positive_numbers= numbers[numbers>=0]
negative_numbers= numbers[numbers<0]

print(f"positive_numbers:{positive_numbers}")
print(f"negative_numbers:{negative_numbers}")


TypeError: 'builtin_function_or_method' object is not subscriptable

Math operations
- sum
- product
- cumsum
- cumprod


In [ ]:
salaries = np.array([30000,50000, 90000,150000,200000,350000,500000])
sum_of_salaries = np.sum(salaries)
print(sum_of_salaries)

1370000


In [ ]:
cum_salaries = np.cumsum(salaries)
print(cum_salaries)

[  30000   80000  170000  320000  520000  870000 1370000]


In [ ]:
prod_cumulatives = np.cumprod(salaries)
print(salaries)
print(prod_cumulatives)

[ 30000  50000  90000 150000 200000 350000 500000]
[               30000           1500000000      135000000000000
  1803255926290448384 -1108127005766844416 -1657868652222873600
  7012328849320968192]


Due to large numbers, the cumulative product values quickly escalate to the point where they exceed numerical limit of datatypes on the python programming language, leading to integral overflow. This is why some numbers appear as negative values.

NaN - Not a Number(Null values)
-We can generate a NaN value using np.nan

-NaN values are used to do the following:

1.   Handle missing values
2.   Helps with computations since it wont return errors but instead ,returns np.
3. Helps filter out or fill in missing values in pandas.



In [ ]:
numbers_with_nans = np.array([10,np.nan, 20,30,np.nan,50,60])
print(numbers_with_nans)

[10. nan 20. 30. nan 50. 60.]
